name: idoc
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: GitHubNotifier
          description: A lightweight macOS menubar hub for your GitHub works. Menubar-first workflow, Unified Issues/PRs list, and more.
          keywords: macOS, GitHub, Notifier, Menubar, SwiftUI, Developer Tools
          favicon: Sources/GitHubNotifier/Resources/Assets.xcassets/AppIcon.appiconset/icon_256.png
          logo: Sources/GitHubNotifier/Resources/Assets.xcassets/AppIcon.appiconset/icon_256.png

          openSource: https://github.com/samzong/GitHubNotifier

          tocs: false

          element:
            wrapper: style=max-width:720px;

          menus:
            Home: index.html
            About:
              url: https://github.com/samzong
              target: __blank
          sideEffectFiles:
            - README_zh.md
          
          cacheFileStat: true

          footer: |
            Copyright Â© {{idocYear}} <a href="https://github.com/samzong" target="_blank">samzong</a><br />
            <script>
              function downloadLatest() {
                const platform = navigator.platform.toLowerCase();
                const userAgent = navigator.userAgent.toLowerCase();
                
                let downloadUrl = '';
                
                if (platform.includes('mac')) {
                  // macOS
                  if (userAgent.includes('arm') || userAgent.includes('apple')) {
                    downloadUrl = 'https://github.com/samzong/GitHubNotifier/releases/latest/download/GitHubNotifier-arm64.dmg';
                  } else {
                    downloadUrl = 'https://github.com/samzong/GitHubNotifier/releases/latest/download/GitHubNotifier-x86_64.dmg';
                  }
                } else {
                  // other
                  window.open('https://github.com/samzong/GitHubNotifier/releases/latest', '_blank');
                  return;
                }
                window.location.href = downloadUrl;
              }
            </script>
          EOF

      - run: npm install idoc@1 -g
      - run: idoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
